---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-servicenow-service
  labels:
    "app": "keptn"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-servicenow-service-secrets
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-servicenow-service-secrets
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-servicenow-service-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-servicenow-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicenow-service
spec:
  selector:
    matchLabels:
      run: servicenow-service
  replicas: 1
  template:
    metadata:
      labels:
        run: servicenow-service
    spec:
      serviceAccountName: keptn-servicenow-service      
      containers:
      - name: servicenow-service
        image: keptn-contrib/servicenow-service:0.3.0
        ports:
         - containerPort: 8080
        env:
          - name: EVENTBROKER
            value: 'http://localhost:8081/event'
          - name: CONFIGURATION_SERVICE
            value: 'http://configuration-service:8080'
      - name: distributor
        image: keptn/distributor:0.8.3
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "250m"
        env:
          - name: PUBSUB_URL
            value: 'nats://keptn-nats-cluster'
          - name: PUBSUB_TOPIC
            value: 'sh.keptn.>'
          - name: PUBSUB_RECIPIENT
            value: '127.0.0.1'

---
apiVersion: v1
kind: Service
metadata:
  name: servicenow-service
  labels:
    run: servicenow-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: servicenow-service